version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongo-data:/var/lib/demo

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:8082
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:test@mongo:27017
      MY_JWT: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
    depends_on:
      - mongo

volumes:
  mongo-data:  # Declares the volume to persist MongoDB data